### ISSUE TITLE
Logs management

### ISSUE THREAD

**Issue by pascalandy** [botleg/swarm-monitoring#1]
Hi,
Very cool post on https://botleg.com/stories/monitoring-docker-swarm-with-cadvisor-influxdb-and-grafana/

Got a question for you. Is there a way to prevent log to become too big ? i.e. could we keep only keep 7 days of activities ?

Cheers!

**Comment by hanzeljesheen** [comment]
Are you talking about storing only 7 days of metrics in InfluxDB?

**Comment by pascalandy** [comment]
Correct. Or if you prefer, at high level, how can we make sure logs are not filling all disk space.

Cheers!

**Comment by hanzeljesheen** [comment]
You can set a `Retention Policy` for InfluxDB databse for the `cadvisor` database for 7 days. There are two ways of doing this:
* Set retention duration while creating the database with, 
```bash
docker exec `docker ps | grep -i influx | awk '{print $1}'` influx -execute 'CREATE DATABASE cadvisor WITH DURATION 7d'
```
* If the database is already created, add a retention policy for it with,
```bash
docker exec `docker ps | grep -i influx | awk '{print $1}'` influx -execute 'CREATE RETENTION POLICY sevendays ON cadvisor DURATION 7d REPLICATION 1'
```

Does this solve your problem?

**Comment by pascalandy** [comment]
This is exactly it!! Thank you very much. I think this should be part of the README :)
