### ISSUE TITLE
unknown option: rw

### ISSUE THREAD

**Issue by Ti-webdev** [botleg/swarm-monitoring#2]
`invalid spec: /var/run:/var/run:rw: unknown option: rw`

**Comment by Ti-webdev** [comment]
docker-compose version 1.12.0, build b31ff33

**Comment by hanzeljesheen** [comment]
Is it working when you remove `:rw` from the `docker-stack.yml` file. Also, could you give the version of your docker engine?

**Comment by Ti-webdev** [comment]
Yes, without `:rw` it works.
Docker version 17.04.0-ce

**Comment by hanzeljesheen** [comment]
I believe that this is an issue with Docker 17.04.0-ce. Check [here](https://github.com/moby/moby/issues/32398). Can I close this issue.
