### ISSUE TITLE
Database not found error

### ISSUE THREAD

**Issue by Franklin89** [botleg/swarm-monitoring#3]
If I deploy the stack file and all the services are running I keep getting the following error when I add the datasource:

```
DB Not found
Could not find the specified database name.
```

If I check the logs from the cadvisor container I see this error

```
E0623 11:32:01.239160       1 memory.go:91] failed to write stats to influxDb - {"error":"database not found: \"cadvisor\""}
```

Any seems like there is something missing...but not sure how to fix this.

**Comment by hanzeljesheen** [comment]
You need to create a database name `cadvisor` to store the metrics with the following command: ```
docker exec `docker ps | grep -i influx | awk '{print $1}'` influx -execute 'CREATE DATABASE cadvisor'```

**Comment by Franklin89** [comment]
Two seconds after I clicked Create Issue I was like tadaaa simple you missed out a step...sorry for bugging you with such stupid questions...

**Comment by hanzeljesheen** [comment]
No worries, just happy to help.
